import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Sidebar from "../components/SideBar";
import { Providers } from "./providers";
import { Toaster } from "../components/ui/toaster"



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Chessmasters- multuplayer chess game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Providers>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex">
              <div className="bg-slate-800 h-screen	">
                <Sidebar />
              </div>
              <div>
                {children}
                <Toaster />

              </div>
            </div>
        </ ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
